

exampleGod = {
    "GodName":'ExampleName',
    "GodClass": 'ExampleClass',
    "DamageType":'ExampleDamageType',
    "BaseHP":0.0,
    "HpPerLvl":0.0,
    "BaseMP": 0.0,
    "MpPerLvl": 0.0,
    "BaseSpeed": 0.0,
    "SpeedPerLvl": 0.0,
    "Range": 0.0,
    "RangePerLvl": 0.0,
    "BaseAPS": 0.0,
    "ApsPerLvl": 0.0,
    "BaseATP": 0.0,
    "AtpPerLvl": 0.0,
    "BasePhysDef": 0.0,
    "PhysDefPerLvl": 0.0,
    "BaseMagDef": 0.0,
    "MagDefPerLvl": 0.0,
    "BaseHP5": 0.0,
    "HP5PerLvl": 0.0,
    "BaseMP5": 0.0,
    "MP5PerLvl": 0.0,
    'CDR':0.0,
    'LifeSteal':0.0,
    'Passives': 'PassiveID'
              }


MageGods = [
    'Agni',
    'AhPuch',
    'Anubis',
    'AoKuang',
    'Aphrodite',
    "Chang'e",
    'Chronos',
    'Freya',
    'Hades',
    'HeBo',
    'Hel',
    'Isis',
    'Janus',
    'Kukulkan',
    'Nox',
    'NuWa',
    'Poseidon',
    'Ra',
    'Raijin',
    'Scylla',
    'Sol',
    'TheMorrigan',
    'Thoth',
    'Vulcan',
    'Zeus',
    'ZhongKui'
]

AssassinGods = [
    'Arachne',
    'Awilix',
    'Bakasura',
    'Bastet',
    'Camazotz',
    'Fenrir',
    'HunBatz',
    'Kali',
    'Loki',
    'Mercury',
    'NeZha',
    'Nemesis',
    'Ratatosker',
    'Serqet',
    'Susano',
    'Thanatos',
    'Thor',
]

GuardianGods = [
    'Ares',
    'Athena',
    'Bacchus',
    'Cabrakan',
    'Fafnir',
    'Geb',
    'Khepri',
    'Kumbhakarna',
    'Kuzenbo',
    'Sobek',
    'Sylvanus',
    'Terra',
    'Xing Tian',
    'Ymir',
]

HunterGods = [
    'AhMuzenCab',
    'Anhur',
    'Apollo',
    'Artemis',
    'Cernunnos',
    'Chiron',
    'Cupid',
    'HouYi',
    'Izanami',
    'JingWei',
    'Medusa',
    'Neith',
    'Rama',
    'Skadi',
    'Ullr',
    'Xbalanque',
]

WarriorGods = [
    'Amaterasu',
    'Bellona',
    'Chaac',
    'ErlangShen',
    'GuanYu',
    'Hercules',
    'Nike',
    'Odin',
    'Osiris',
    'Ravana',
    'SunWukong',
    'Tyr',
    'Vamana',
]

AllGods = [
    'Agni',
    'AhPuch',
    'Anubis',
    'AoKuang',
    'Aphrodite',
    "Chang'e",
    'Chronos',
    'Freya',
    'Hades',
    'HeBo',
    'Hel',
    'Isis',
    'Janus',
    'Kukulkan',
    'Nox',
    'NuWa',
    'Poseidon',
    'Ra',
    'Raijin',
    'Scylla',
    'Sol',
    'TheMorrigan',
    'Thoth',
    'Vulcan',
    'Zeus',
    'Zhong Kui',
    'Arachne',
    'Awilix',
    'Bakasura',
    'Bastet',
    'Camazotz',
    'Fenrir',
    'Hun Batz',
    'Kali',
    'Loki',
    'Mercury',
    'NeZha',
    'Nemesis',
    'Ratatosker',
    'Serqet',
    'Susano',
    'Thanatos',
    'Thor',
    'Ares',
    'Athena',
    'Bacchus',
    'Cabrakan',
    'Fafnir',
    'Geb',
    'Khepri',
    'Kumbhakarna',
    'Kuzenbo',
    'Sobek',
    'Sylvanus',
    'Terra',
    'XingTian',
    'Ymir',
    'AhMuzenCab',
    'Anhur',
    'Apollo',
    'Artemis',
    'Cernunnos',
    'Chiron',
    'Cupid',
    'HouYi',
    'Izanami',
    'JingWei',
    'Medusa',
    'Neith',
    'Rama',
    'Skadi',
    'Ullr',
    'Xbalanque',
    'Amaterasu',
    'Bellona',
    'Chaac',
    'ErlangShen',
    'GuanYu',
    'Hercules',
    'Nike',
    'Odin',
    'Osiris',
    'Ravana',
    'SunWukong',
    'Tyr',
    'Vamana',
]


phrases = [
    ', you should play ',
    ', you would do great if you played ',
    ', you will wreck, if you play ',
    ', just play ',
    ', you + the need to win = you playing ',
    ", you'll win if you play ",
    ', will win if they play ',
    ', will melt face if they play ',
    ', will dominate if they play ',
    ', will be playing ',
]