exampleGod = {
    "GodName":'ExampleName',
    "GodClass": 'ExampleClass',
    "DamageType":'ExampleDamageType',
    "BaseHP":0.0,
    "HpPerLvl":0.0,
    "BaseMP": 0.0,
    "MpPerLvl": 0.0,
    "BaseSpeed": 0.0,
    "SpeedPerLvl": 0.0,
    "Range": 0.0,
    "RangePerLvl": 0.0,
    "BaseAPS": 0.0,
    "ApsPerLvl": 0.0,
    "BaseATP": 0.0,
    "AtpPerLvl": 0.0,
    "BasePhysDef": 0.0,
    "PhysDefPerLvl": 0.0,
    "BaseMagDef": 0.0,
    "MagDefPerLvl": 0.0,
    "BaseHP5": 0.0,
    "HP5PerLvl": 0.0,
    "BaseMP5": 0.0,
    "MP5PerLvl": 0.0,
    'CDR':0.0,
    'LifeSteal':0.0,
    'Passives': 'PassiveID'
              }

example2 = {
    "GodName":'',
    "GodClass": '',
    "DamageType":'',
    "BaseHP":0.0,
    "HpPerLvl":0.0,
    "BaseMP": 0.0,
    "MpPerLvl": 0.0,
    "BaseSpeed": 0.0,
    "SpeedPerLvl": 0.0,
    "Range": 0.0,
    "RangePerLvl": 0.0,
    "BaseAPS": 0.0,
    "ApsPerLvl": 0.0,
    "BaseATP": 0.0,
    "AtpPerLvl": 0.0,
    "BasePhysDef": 0.0,
    "PhysDefPerLvl": 0.0,
    "BaseMagDef": 0.0,
    "MagDefPerLvl": 0.0,
    "BaseHP5": 0.0,
    "HP5PerLvl": 0.0,
    "BaseMP5": 0.0,
    "MP5PerLvl": 0.0,
    'CDR':0.0,
    'LifeSteal':0.0,
    'Passives': ''
              }




Agni = {
    "GodName":'AGNI',
    "GodClass": 'MAGE',
    "DamageType":'MAGICAL',
    "BaseHP":431.0,
    "HpPerLvl":71.0,
    "BaseMP": 300.0,
    "MpPerLvl": 45.0,
    "BaseSpeed": 350.0,
    "SpeedPerLvl": 0.0,
    "Range": 55.0,
    "RangePerLvl": 0.0,
    "BaseAPS": 1.01,
    "ApsPerLvl": 0.01,
    "BaseATP": 36.0,
    "AtpPerLvl": 1.5,
    "BasePhysDef": 14.0,
    "PhysDefPerLvl": 2.60,
    "BaseMagDef": 30.0,
    "MagDefPerLvl": 0.0,
    "BaseHP5": 7.5,
    "HP5PerLvl": 0.47,
    "BaseMP5": 5.1,
    "MP5PerLvl": 0.37,
    'CDR':0.0,
    'LifeSteal':0.0,
    'Passives': ''
              }


AMC =  {
    "GodName":'Ah Muzen Cab',
    "GodClass": 'Hunter',
    "DamageType":'Physical',
    "BaseHP":523.0,
    "HpPerLvl":71.0,
    "BaseMP": 300.0,
    "MpPerLvl": 45.0,
    "BaseSpeed": 365.0,
    "SpeedPerLvl": 0.0,
    "Range": 55.0,
    "RangePerLvl": 0.0,
    "BaseAPS": 0.97,
    "ApsPerLvl": 0.017,
    "BaseATP": 40.0,
    "AtpPerLvl": 2.20,
    "BasePhysDef": 15.0,
    "PhysDefPerLvl": 3.0,
    "BaseMagDef": 31.0,
    "MagDefPerLvl": 0.9,
    "BaseHP5": 7.7,
    "HP5PerLvl": 0.71,
    "BaseMP5": 4.8,
    "MP5PerLvl": 0.38,
    'CDR':0.0,
    'LifeSteal':0.0,
    'Passives': ''
              }

Arachne =  {
    "GodName":'Arachne',
    "GodClass": 'Assassin',
    "DamageType":'Physical',
    "BaseHP":524.0,
    "HpPerLvl":79.0,
    "BaseMP": 251.0,
    "MpPerLvl": 41.0,
    "BaseSpeed": 375.0,
    "SpeedPerLvl": 0.0,
    "Range": 12.0,
    "RangePerLvl": 0.0,
    "BaseAPS": 1.04,
    "ApsPerLvl": 0.02,
    "BaseATP": 42.0,
    "AtpPerLvl": 2.20,
    "BasePhysDef": 19.0,
    "PhysDefPerLvl": 3.0,
    "BaseMagDef": 31.0,
    "MagDefPerLvl": 0.9,
    "BaseHP5": 9.7,
    "HP5PerLvl": 0.67,
    "BaseMP5": 5.3,
    "MP5PerLvl": 0.46,
    'CDR':0.0,
    'LifeSteal':0.0,
    'Passives': ''
              }