exampleGod = {
    "GodName":'ExampleName',
    "GodClass": 'ExampleClass',
    "DamageType":'ExampleDamageType',
    "BaseHP":0.0,
    "HpPerLvl":0.0,
    "BaseMP": 0.0,
    "MpPerLvl": 0.0,
    "BaseSpeed": 0.0,
    "SpeedPerLvl": 0.0,
    "Range": 0.0,
    "RangePerLvl": 0.0,
    "BaseAPS": 0.0,
    "ApsPerLvl": 0.0,
    "BaseATP": 0.0,
    "AtpPerLvl": 0.0,
    "BasePhysDef": 0.0,
    "PhysDefPerLvl": 0.0,
    "BaseMagDef": 0.0,
    "MagDefPerLvl": 0.0,
    "BaseHP5": 0.0,
    "HP5PerLvl": 0.0,
    "BaseMP5": 0.0,
    "MP5PerLvl": 0.0,
    'CDR':0.0,
    'LifeSteal':0.0,
    'Passives': 'PassiveID'
              }

example2 = {
    "GodName":'',
    "GodClass": '',
    "DamageType":'',
    "BaseHP":0.0,
    "HpPerLvl":0.0,
    "BaseMP": 0.0,
    "MpPerLvl": 0.0,
    "BaseSpeed": 0.0,
    "SpeedPerLvl": 0.0,
    "Range": 0.0,
    "RangePerLvl": 0.0,
    "BaseAPS": 0.0,
    "ApsPerLvl": 0.0,
    "BaseATP": 0.0,
    "AtpPerLvl": 0.0,
    "BasePhysDef": 0.0,
    "PhysDefPerLvl": 0.0,
    "BaseMagDef": 0.0,
    "MagDefPerLvl": 0.0,
    "BaseHP5": 0.0,
    "HP5PerLvl": 0.0,
    "BaseMP5": 0.0,
    "MP5PerLvl": 0.0,
    'CDR':0.0,
    'LifeSteal':0.0,
    'Passives': ''
              }

Agni = {
    "GodName":'AGNI',
    "GodClass": 'MAGE',
    "DamageType":'MAGICAL',
    "BaseHP":431.0,
    "HpPerLvl":71.0,
    "BaseMP": 300.0,
    "MpPerLvl": 45.0,
    "BaseSpeed": 350.0,
    "SpeedPerLvl": 0.0,
    "Range": 55.0,
    "RangePerLvl": 0.0,
    "BaseAPS": 1.01,
    "ApsPerLvl": 0.01,
    "BaseATP": 36.0,
    "AtpPerLvl": 1.5,
    "BasePhysDef": 14.0,
    "PhysDefPerLvl": 2.60,
    "BaseMagDef": 30.0,
    "MagDefPerLvl": 0.0,
    "BaseHP5": 7.5,
    "HP5PerLvl": 0.47,
    "BaseMP5": 5.1,
    "MP5PerLvl": 0.37,
    'CDR':0.0,
    'LifeSteal':0.0,
    'Passives': ''
              }
